Use pipe.set() when expire is set to None
Error: redis.exceptions.ResponseError: value is not an integer or out of range
Trace: File "/usr/local/lib/python2.7/site-packages/redis_cache/rediscache.py", line 139, in store
    pipe.execute()
Summary: Documentation specifies (None) for no expiration, but code checks for any negative number.
Fix: Check for expire to be None in addition to the preexisting condition.